### ISSUE TITLE
Why not make 'api' scope default?

### ISSUE THREAD

**Issue by mihaineacsu** [fh1ch/passport-gitlab2#5] opened 2017-05-26 15:00 UTC
In what cases would one use only 'read_user' scope?

After the authentication, the profile is retrieved using the `api/v3/user` URL - using only 'read_user' scope will result in 403 error:
`{"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"api"}`

**Comment by fh1ch** [comment] 2017-05-31 10:39
Hi @mihaineacsu 

First of all, sorry for the delayed answer. I investigated a bit and it seems, that the `read_user` scope is indeed the right one to use, as it also worked perfectly fine in GitLab-9.0 to 9.1. However GitLab-9.2 has a regression issue in this are: https://gitlab.com/gitlab-org/gitlab-ce/issues/33022
I therefore hope, that it will be fixed in one of the GitLab patch releases (e.g. `9.2.3`) or at least in the next version (e.g. `9.3.0`).

If you don't want to change the scope grammatically (see https://github.com/fh1ch/passport-gitlab2#how-do-i-change-permissions--scope-when-obtaining-a-user-profile), you can use version `2` of this package (`npm install --save passport-gitlab2@2`) which still has the `api` scope by default.

I hope this helps you.

Cheer

**Comment by fh1ch** [comment] 2018-06-10 20:26
The `read_user` scope is now working again since a couple of GitLab versions and is also the proposed one, when using GitLab as authentication provider. I'm therefore going to close this issue.

**Closed as completed by fh1ch** 2018-06-10 20:26 UTC
Labels: bug, wontfix
